import type { ResumeContent, ResumeTemplate, TargetProfile } from "@/types/resume";

export const templates: ResumeTemplate[] = [
  {
    id: "atlas",
    name: "Atlas 学术序列",
    description: "克制的单栏结构，优先呈现教育、研究与成果。",
    track: "study",
    accent: "#3559e0",
    layout: "classic",
    tags: ["ATS 纯文本", "研究型", "英文"],
    active: true,
    recommendedFor: ["英国 G5", "美国研究生", "博士申请"],
  },
  {
    id: "camber",
    name: "Camber 学院派",
    description: "编辑感标题与清晰层级，适合跨学科背景。",
    track: "study",
    accent: "#7437d1",
    layout: "editorial",
    tags: ["作品集", "跨学科", "双语"],
    active: true,
    recommendedFor: ["艺术与设计", "港新申请", "跨专业"],
  },
  {
    id: "northstar",
    name: "Northstar 研究者",
    description: "高信息密度布局，为论文、实验与奖项预留空间。",
    track: "study",
    accent: "#087c6f",
    layout: "compact",
    tags: ["科研", "奖项", "高密度"],
    active: true,
    recommendedFor: ["理工科", "奖学金", "科研岗位"],
  },
  {
    id: "meridian",
    name: "Meridian 国际申请",
    description: "平衡学术与实践，适合授课型硕士和跨地区申请。",
    track: "study",
    accent: "#b44b67",
    layout: "modern",
    tags: ["授课型", "实践", "双语"],
    active: true,
    recommendedFor: ["港新申请", "授课型硕士", "商科与工程"],
  },
  {
    id: "summit",
    name: "Summit 大厂标准",
    description: "结果导向、结构清晰，强化业务影响与技术关键词。",
    track: "career",
    accent: "#1859c9",
    layout: "modern",
    tags: ["大厂", "技术", "ATS 纯文本"],
    active: true,
    recommendedFor: ["互联网", "产品", "研发"],
  },
  {
    id: "pillar",
    name: "Pillar 国企稳健",
    description: "端庄、可信、结构严谨，突出组织经历与综合素质。",
    track: "career",
    accent: "#9c3529",
    layout: "classic",
    tags: ["国企", "央企", "管培"],
    active: true,
    recommendedFor: ["央企", "金融", "公共事业"],
  },
  {
    id: "signal",
    name: "Signal 创新表达",
    description: "鲜明但不过度设计，适合增长、品牌与创意岗位。",
    track: "career",
    accent: "#d4562c",
    layout: "editorial",
    tags: ["创意", "增长", "品牌"],
    active: true,
    recommendedFor: ["市场", "设计", "新消费"],
  },
  {
    id: "forge",
    name: "Forge 技术深潜",
    description: "强化技术栈、系统边界与工程指标，适合研发岗位。",
    track: "career",
    accent: "#3f4b57",
    layout: "compact",
    tags: ["研发", "工程", "高密度"],
    active: true,
    recommendedFor: ["后端研发", "算法", "基础架构"],
  },
];

export const targetProfiles: TargetProfile[] = [
  {
    id: "cambridge",
    track: "study",
    name: "剑桥大学",
    category: "英国 G5",
    region: "英国",
    description: "强调学术准备、研究潜力和与目标课程的明确连接。",
    keywords: ["research readiness", "academic rigor", "independent inquiry", "methods"],
    priorities: ["教育与课程匹配", "研究/论文成果", "可验证的学术能力"],
    tone: "严谨、具体、证据驱动",
  },
  {
    id: "stanford",
    track: "study",
    name: "斯坦福大学",
    category: "美国名校",
    region: "美国",
    description: "兼顾卓越、主动性、领导力与真实影响。",
    keywords: ["initiative", "impact", "leadership", "intellectual vitality"],
    priorities: ["独特轨迹", "跨领域影响", "主动创造的成果"],
    tone: "自信、鲜活、影响导向",
  },
  {
    id: "nus",
    track: "study",
    name: "新加坡国立大学",
    category: "亚洲名校",
    region: "新加坡",
    description: "突出扎实能力、国际视野和实践落地。",
    keywords: ["technical depth", "global perspective", "application", "collaboration"],
    priorities: ["量化学术表现", "项目实践", "多元协作"],
    tone: "清晰、务实、国际化",
  },
  {
    id: "hku",
    track: "study",
    name: "香港大学",
    category: "亚洲名校",
    region: "中国香港",
    description: "兼顾学术能力、国际表达与实践关联，突出与申请方向的清晰匹配。",
    keywords: ["academic foundation", "global outlook", "application", "communication"],
    priorities: ["课程与项目匹配", "英语与国际表达", "可落地的实践成果"],
    tone: "专业、清楚、国际化",
  },
  {
    id: "state-grid",
    track: "career",
    name: "国家电网",
    category: "央企/国企",
    region: "中国",
    description: "强调专业匹配、稳定执行、责任意识与团队协作。",
    keywords: ["专业能力", "安全意识", "责任担当", "协同执行"],
    priorities: ["专业/证书匹配", "组织与实践经历", "可靠性与规范意识"],
    tone: "稳健、正式、可信",
  },
  {
    id: "huawei",
    track: "career",
    name: "华为",
    category: "科技大厂",
    region: "中国",
    description: "突出技术纵深、复杂问题解决与持续交付。",
    keywords: ["技术深度", "艰苦问题", "客户价值", "规模化交付"],
    priorities: ["硬核项目", "量化结果", "压力下的闭环能力"],
    tone: "直接、专业、结果导向",
  },
  {
    id: "tencent",
    track: "career",
    name: "腾讯",
    category: "互联网大厂",
    region: "中国",
    description: "强调用户价值、数据判断、协作与产品影响。",
    keywords: ["用户价值", "数据驱动", "跨团队协作", "业务影响"],
    priorities: ["指标变化", "角色边界", "方法与复盘"],
    tone: "简洁、敏捷、可量化",
  },
  {
    id: "bytedance",
    track: "career",
    name: "字节跳动",
    category: "互联网大厂",
    region: "中国",
    description: "突出高标准、快速迭代、数据敏感和开放协作。",
    keywords: ["高标准", "快速迭代", "数据敏感", "坦诚清晰"],
    priorities: ["高杠杆成果", "迭代速度", "数据闭环"],
    tone: "高密度、量化、行动导向",
  },
];

export const createStarterContent = (track: "study" | "career"): ResumeContent => ({
  basics: {
    name: "林知远",
    email: "lin.zhiyuan@example.com",
    phone: "+86 138 0000 0000",
    location: "上海，中国",
    website: "linkedin.com/in/zhiyuan-lin",
    headline: track === "study" ? "Computer Science · Research Applicant" : "产品策略 · 数据增长",
  },
  summary:
    track === "study"
      ? "计算机科学本科生，关注人机协作与可信机器学习。通过研究和跨学科项目，把技术问题转化为可验证的实验与真实影响。"
      : "具备产品、数据与增长交叉经验的应届生，擅长从用户问题出发建立指标、推动协作并交付可量化结果。",
  education: [
    {
      id: "edu-1",
      school: "同济大学",
      degree: "工学学士",
      major: "计算机科学与技术",
      startDate: "2022.09",
      endDate: "2026.06",
      location: "上海",
      score: "GPA 3.82/4.0 · 专业前 8%",
      highlights: ["核心课程：机器学习、数据库系统、算法设计", "校级一等奖学金（2 次）"],
    },
  ],
  experience: [
    {
      id: "exp-1",
      organization: track === "study" ? "智能交互实验室" : "某头部互联网公司",
      role: track === "study" ? "本科研究助理" : "产品策略实习生",
      startDate: "2025.03",
      endDate: "2025.09",
      location: "上海",
      bullets:
        track === "study"
          ? ["设计并实现 3 组用户实验，覆盖 126 名参与者", "建立可复现实验管线，将数据清洗时间降低 42%"]
          : ["分析 18 万条用户路径，定位首周留存的两个关键断点", "联合设计与研发上线 3 次实验，使激活率提升 12.6%"],
    },
  ],
  projects: [
    {
      id: "project-1",
      name: "Campus Copilot",
      role: "项目负责人",
      date: "2025",
      link: "github.com/example/campus-copilot",
      bullets: ["带领 4 人团队完成从访谈、原型到部署的完整闭环", "在 6 周试点中服务 500+ 学生，任务完成率提升 31%"],
    },
  ],
  skills: ["Python", "TypeScript", "SQL", "Figma", "数据分析"],
  languages: ["中文（母语）", "英语（IELTS 7.5）"],
  awards: ["全国大学生创新创业竞赛二等奖", "同济大学优秀学生"],
});

export const createBlankContent = (): ResumeContent => ({
  basics: {
    name: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    headline: "",
  },
  summary: "",
  education: [],
  experience: [],
  projects: [],
  skills: [],
  languages: [],
  awards: [],
});
