import type { ResumeContent, ResumeTemplate } from "@/types/resume";

export { targetCatalogGroups, targetProfiles } from "@/lib/target-catalog";

export const templates: ResumeTemplate[] = [
  {
    id: "atlas",
    name: "Atlas 学术序列",
    description: "克制的单栏结构，优先呈现教育、研究与成果。",
    track: "study",
    accent: "#3559e0",
    layout: "classic",
    tags: ["ATS 纯文本", "研究型", "英文"],
    active: true,
    recommendedFor: ["英国 G5", "美国研究生", "博士申请"],
  },
  {
    id: "camber",
    name: "Camber 学院派",
    description: "编辑感标题与清晰层级，适合跨学科背景。",
    track: "study",
    accent: "#7437d1",
    layout: "editorial",
    tags: ["作品集", "跨学科", "双语"],
    active: true,
    recommendedFor: ["艺术与设计", "港新申请", "跨专业"],
  },
  {
    id: "northstar",
    name: "Northstar 研究者",
    description: "高信息密度布局，为论文、实验与奖项预留空间。",
    track: "study",
    accent: "#087c6f",
    layout: "compact",
    tags: ["科研", "奖项", "高密度"],
    active: true,
    recommendedFor: ["理工科", "奖学金", "科研岗位"],
  },
  {
    id: "meridian",
    name: "Meridian 国际申请",
    description: "平衡学术与实践，适合授课型硕士和跨地区申请。",
    track: "study",
    accent: "#b44b67",
    layout: "modern",
    tags: ["授课型", "实践", "双语"],
    active: true,
    recommendedFor: ["港新申请", "授课型硕士", "商科与工程"],
  },
  {
    id: "harbour",
    name: "Harbour 港新简明",
    description: "紧凑的国际申请结构，平衡课程、项目与实践证据。",
    track: "study",
    accent: "#0f766e",
    layout: "modern",
    tags: ["香港", "新加坡", "授课型"],
    active: true,
    recommendedFor: ["香港院校", "新加坡院校", "国际化项目"],
  },
  {
    id: "oxbridge",
    name: "Oxbridge 学术严谨",
    description: "克制的研究型排版，强化方法、论文与学术准备。",
    track: "study",
    accent: "#243b6b",
    layout: "classic",
    tags: ["英国", "研究型", "方法证据"],
    active: true,
    recommendedFor: ["英国研究型项目", "博士申请", "奖学金"],
  },
  {
    id: "pacific",
    name: "Pacific 澳洲实践",
    description: "清晰呈现教育与实践连接，适合职业导向和跨专业项目。",
    track: "study",
    accent: "#1677a3",
    layout: "modern",
    tags: ["澳洲", "实践", "职业连接"],
    active: true,
    recommendedFor: ["澳洲院校", "授课型硕士", "跨专业"],
  },
  {
    id: "continental",
    name: "Continental 欧陆项目",
    description: "强调专业深度、项目方法与跨文化经历的编辑式布局。",
    track: "study",
    accent: "#7b3f55",
    layout: "editorial",
    tags: ["欧洲", "跨文化", "项目方法"],
    active: true,
    recommendedFor: ["欧洲大陆", "国际项目", "商科与社科"],
  },
  {
    id: "summit",
    name: "Summit 大厂标准",
    description: "结果导向、结构清晰，强化业务影响与技术关键词。",
    track: "career",
    accent: "#1859c9",
    layout: "modern",
    tags: ["大厂", "技术", "ATS 纯文本"],
    active: true,
    recommendedFor: ["互联网", "产品", "研发"],
  },
  {
    id: "pillar",
    name: "Pillar 国企稳健",
    description: "端庄、可信、结构严谨，突出组织经历与综合素质。",
    track: "career",
    accent: "#9c3529",
    layout: "classic",
    tags: ["国企", "央企", "管培"],
    active: true,
    recommendedFor: ["央企", "金融", "公共事业"],
  },
  {
    id: "signal",
    name: "Signal 创新表达",
    description: "鲜明但不过度设计，适合增长、品牌与创意岗位。",
    track: "career",
    accent: "#d4562c",
    layout: "editorial",
    tags: ["创意", "增长", "品牌"],
    active: true,
    recommendedFor: ["市场", "设计", "新消费"],
  },
  {
    id: "forge",
    name: "Forge 技术深潜",
    description: "强化技术栈、系统边界与工程指标，适合研发岗位。",
    track: "career",
    accent: "#3f4b57",
    layout: "compact",
    tags: ["研发", "工程", "高密度"],
    active: true,
    recommendedFor: ["后端研发", "算法", "基础架构"],
  },
  {
    id: "statecraft",
    name: "Statecraft 央企校招",
    description: "正式、稳健的校园招聘结构，突出专业匹配与组织协作。",
    track: "career",
    accent: "#8b2f2f",
    layout: "classic",
    tags: ["央企", "国企", "校招"],
    active: true,
    recommendedFor: ["能源通信", "国有金融", "基建制造"],
  },
  {
    id: "sterling",
    name: "Sterling 国际金融",
    description: "高密度、数字敏感的专业版式，强调分析、案例与交付。",
    track: "career",
    accent: "#183a56",
    layout: "compact",
    tags: ["投行", "金融", "咨询"],
    active: true,
    recommendedFor: ["国际投行", "证券", "专业服务"],
  },
  {
    id: "orbit",
    name: "Orbit 全球科技",
    description: "兼顾技术深度与国际协作，突出所有权和规模化影响。",
    track: "career",
    accent: "#3156c8",
    layout: "modern",
    tags: ["全球科技", "云计算", "产品研发"],
    active: true,
    recommendedFor: ["国际科技", "跨国协作", "技术产品"],
  },
  {
    id: "venture",
    name: "Venture 商业与品牌",
    description: "清晰表达洞察、策略与跨职能执行，适合咨询、快消和品牌岗位。",
    track: "career",
    accent: "#9a4b20",
    layout: "editorial",
    tags: ["咨询", "快消", "品牌"],
    active: true,
    recommendedFor: ["战略咨询", "快消品牌", "市场与运营"],
  },
];

export const createStarterContent = (track: "study" | "career"): ResumeContent => ({
  basics: {
    name: "林知远",
    email: "lin.zhiyuan@example.com",
    phone: "+86 138 0000 0000",
    location: "上海，中国",
    website: "linkedin.com/in/zhiyuan-lin",
    headline: track === "study" ? "Computer Science · Research Applicant" : "产品策略 · 数据增长",
  },
  summary:
    track === "study"
      ? "计算机科学本科生，关注人机协作与可信机器学习。通过研究和跨学科项目，把技术问题转化为可验证的实验与真实影响。"
      : "具备产品、数据与增长交叉经验的应届生，擅长从用户问题出发建立指标、推动协作并交付可量化结果。",
  education: [
    {
      id: "edu-1",
      school: "同济大学",
      degree: "工学学士",
      major: "计算机科学与技术",
      startDate: "2022.09",
      endDate: "2026.06",
      location: "上海",
      score: "GPA 3.82/4.0 · 专业前 8%",
      highlights: ["核心课程：机器学习、数据库系统、算法设计", "校级一等奖学金（2 次）"],
    },
  ],
  experience: [
    {
      id: "exp-1",
      organization: track === "study" ? "智能交互实验室" : "某头部互联网公司",
      role: track === "study" ? "本科研究助理" : "产品策略实习生",
      startDate: "2025.03",
      endDate: "2025.09",
      location: "上海",
      bullets:
        track === "study"
          ? ["设计并实现 3 组用户实验，覆盖 126 名参与者", "建立可复现实验管线，将数据清洗时间降低 42%"]
          : ["分析 18 万条用户路径，定位首周留存的两个关键断点", "联合设计与研发上线 3 次实验，使激活率提升 12.6%"],
    },
  ],
  projects: [
    {
      id: "project-1",
      name: "Campus Copilot",
      role: "项目负责人",
      date: "2025",
      link: "github.com/example/campus-copilot",
      bullets: ["带领 4 人团队完成从访谈、原型到部署的完整闭环", "在 6 周试点中服务 500+ 学生，任务完成率提升 31%"],
    },
  ],
  skills: ["Python", "TypeScript", "SQL", "Figma", "数据分析"],
  languages: ["中文（母语）", "英语（IELTS 7.5）"],
  awards: ["全国大学生创新创业竞赛二等奖", "同济大学优秀学生"],
});

export const createBlankContent = (): ResumeContent => ({
  basics: {
    name: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    headline: "",
  },
  summary: "",
  education: [],
  experience: [],
  projects: [],
  skills: [],
  languages: [],
  awards: [],
});
