import { strToU8, zipSync } from "fflate";
import { describe, expect, it } from "vitest";
import { assertSafeLocalDocx, assertSafeLocalImage } from "@/lib/local-file-safety";
import { toDocxBlob } from "@/lib/resume-docx";
import { createStarterContent } from "@/lib/sample-data";
import type { ResumeRecord } from "@/types/resume";

describe("local DOCX safety preflight", () => {
  it("accepts the DOCX generated by the product", async () => {
    const resume: ResumeRecord = {
      id: "00000000-0000-4000-8000-000000000001",
      userId: "user-1",
      title: "安全 DOCX",
      track: "career",
      targetName: "目标公司",
      templateId: "summit",
      status: "draft",
      progress: 100,
      revision: 1,
      content: createStarterContent("career"),
      createdAt: "2026-09-01T00:00:00.000Z",
      updatedAt: "2026-09-01T00:00:00.000Z",
    };
    const blob = await toDocxBlob(resume);
    const arrayBuffer = await blob.arrayBuffer();
    await expect(assertSafeLocalDocx(arrayBuffer)).resolves.toBeUndefined();
  });

  it("rejects archives without the Word document part", async () => {
    const bytes = zipSync({ "readme.txt": strToU8("not a document") });
    await expect(assertSafeLocalDocx(bytes.slice().buffer)).rejects.toThrow(/不是有效的 DOCX/);
  });

  it("rejects traversal-like internal paths", async () => {
    const bytes = zipSync({
      "word/document.xml": strToU8("<document />"),
      "../outside.xml": strToU8("unsafe"),
    });
    await expect(assertSafeLocalDocx(bytes.slice().buffer)).rejects.toThrow(/不安全的内部路径/);
  });

  it("bounds styles and XML complexity before full Word conversion", async () => {
    const styles = zipSync({ "word/document.xml": strToU8("<document />"), "word/styles.xml": new Uint8Array(1_000_001) });
    await expect(assertSafeLocalDocx(styles.slice().buffer)).rejects.toThrow(/解压后的体积异常/);
    const nodes = zipSync({ "word/document.xml": strToU8("<p/>".repeat(120_001)) });
    await expect(assertSafeLocalDocx(nodes.slice().buffer)).rejects.toThrow(/结构过于复杂/);
  });

  it("counts actual inflated bytes instead of trusting forged ZIP size metadata", async () => {
    const bytes = zipSync({ "word/document.xml": new Uint8Array(17_000_000) }, { level: 9 });
    for (let index = 0; index <= bytes.length - 4; index += 1) {
      const signature = bytes[index]
        | (bytes[index + 1] << 8)
        | (bytes[index + 2] << 16)
        | (bytes[index + 3] << 24);
      if (signature === 0x04034b50) new DataView(bytes.buffer, bytes.byteOffset).setUint32(index + 22, 100, true);
      if (signature === 0x02014b50) new DataView(bytes.buffer, bytes.byteOffset).setUint32(index + 24, 100, true);
    }
    await expect(assertSafeLocalDocx(bytes.slice().buffer)).rejects.toThrow(/解压后的体积异常/);
  });
});

describe("local image safety preflight", () => {
  function pngHeader(width: number, height: number) {
    const bytes = new Uint8Array(24);
    bytes.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], 0);
    bytes.set([0x49, 0x48, 0x44, 0x52], 12);
    const view = new DataView(bytes.buffer);
    view.setUint32(16, width);
    view.setUint32(20, height);
    return bytes.buffer;
  }

  it("accepts a bounded image whose bytes match its declared type", () => {
    expect(assertSafeLocalImage(pngHeader(1200, 1600), "image/png")).toMatchObject({
      type: "image/png",
      width: 1200,
      height: 1600,
    });
  });

  it("rejects MIME mismatches and oversized pixel dimensions", () => {
    expect(() => assertSafeLocalImage(pngHeader(1200, 1600), "image/jpeg")).toThrow(/不一致/);
    expect(() => assertSafeLocalImage(pngHeader(6000, 6000), "image/png")).toThrow(/像素尺寸过大/);
  });

  it("rejects a partial PNG magic signature", () => {
    const bytes = new Uint8Array(pngHeader(100, 100));
    bytes[4] = 0;
    expect(() => assertSafeLocalImage(bytes.buffer, "image/png")).toThrow(/损坏/);
  });
});
